export const APP_LINKS = [
  "/",
  "/about/about-us",
  "/about/confession",
  "/about/contact",
  "/about/hall-rentals",
  "/about/privacy-policy",
  "/about/register",
  "/about/mass-booking",
  "/about/safeguarding",
  "/about/Signing-schools-certificate",
  "/about/subscribe",
  "/mass-times",
  "/news-and-events/announcements",
  "/news-and-events/events",
  "/parish-groups/legion-of-mary",
  "/parish-groups/alter-server",
  "/parish-groups/choir",
  "/parish-groups/youth-group",
  "/sacramental/baptism",
  "/sacramental/become-a-catholic",
  "/sacramental/confirmation",
  "/sacramental/confession",
  "/sacramental/sponsor-form",
  "/sacramental/first-holy-communion",
  "/sacramental/marriage",
  "/sacramental/rcia-form",
] as const;
