export const APP_LINKS = [
  "/",
  "/about/about-us",
  "/about/confession",
  "/about/contact",
  "/about/register",
  "/about/mass-booking",
  "/about/safeguarding",
  "/about/Signing-schools-certificate",
  "/about/streamed-masses-across-the-diocese",
  "/about/subscribe",
  "/mass-times",
  "/news-and-events/announcements",
  "/news-and-events/blog",
  "/news-and-events/events",
  "/news-and-events/news",
  "/parish-groups/legion-of-mary",
  "/parish-groups/mass-server",
  "/parish-groups/choir",
  "/sacramental/adult-confirmation",
  "/sacramental/baptism",
  "/sacramental/confirmation",
  "/sacramental/first-holy-communion",
  "/sacramental/marriage",
  "/sacramental/become-a-catholic",
] as const;
